# MongoDB connection properties
host=localhost
port=27017
username=motacj
password=1224
database=redsocial

# Pool settings
minPoolSize=5
maxPoolSize=50
maxWaitTime=30
maxlifeTime=120
maxIdleTime=120
appName=App